/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/b7Eop1yP142
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Badge } from "@/components/ui/badge"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="bg-card p-6 rounded-lg shadow-lg w-full max-w-3xl">
        <div className="mb-4">
          <h1 className="text-2xl font-bold text-card-foreground">To-Do List</h1>
        </div>
        <div className="mb-4 flex items-center">
          <Input
            type="text"
            placeholder="Add a new task"
            className="w-full px-4 py-2 rounded-md border border-input focus:outline-none focus:ring-1 focus:ring-primary"
          />
          <Button className="ml-4 px-4 py-2 rounded-md text-primary-foreground">Add Task</Button>
        </div>
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Checkbox id="task-1" className="mr-2" />
              <label htmlFor="task-1" className="text-card-foreground">
                Finish the presentation
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="secondary" className="px-2 py-1 text-xs">
                High
              </Badge>
              <div className="text-sm text-muted-foreground">Due: 04/15/2023</div>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted/50">
                <FilePenIcon className="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted/50">
                <TrashIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Checkbox id="task-2" className="mr-2" defaultChecked />
              <label htmlFor="task-2" className="text-card-foreground line-through">
                Buy groceries
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="secondary" className="px-2 py-1 text-xs">
                Medium
              </Badge>
              <div className="text-sm text-muted-foreground">Due: 04/10/2023</div>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted/50">
                <FilePenIcon className="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted/50">
                <TrashIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Checkbox id="task-3" className="mr-2" />
              <label htmlFor="task-3" className="text-[#ff0000] font-bold">
                Call mom
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="secondary" className="px-2 py-1 text-xs">
                Urgent
              </Badge>
              <div className="text-sm text-muted-foreground">Due: 04/20/2023</div>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted/50">
                <FilePenIcon className="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted/50">
                <TrashIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div className="mt-4 flex justify-end">
          <Button variant="secondary" className="px-4 py-2 rounded-md text-muted-foreground">
            Clear Completed Tasks
          </Button>
        </div>
      </div>
    </div>
  )
}

function FilePenIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function TrashIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
